import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Footer from '../comps/footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Example 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className={styles.grid}>
      <h1>Welcome to my homepage</h1>
    </div>
    <div className={styles.grid__item}>
      <h2>What does C.R.U.D stand for?</h2>
    </div>
    <div className={styles.grid__item}>
    <ul>
        <li>Create</li>
        <li>Read</li>
        <li>Update</li>
        <li>Delete</li>
    </ul>
      <button>View all this info</button>
    </div>

    <Link href='/about'>About Page</Link>
    <Link href='/grades'>Grades Page</Link>
    <Link href='/about'>Go Back</Link>

    <footer>In Class Example #1</footer>
    </div>
  )
}
